# SPDX-License-Identifier: MIT
---
# Put the tasks for your role here.

- name: set platform/version specific variables
  include_tasks: tasks/set_vars.yml

# Examples of some tasks:
- name: Ensure required packages are installed
  package:
    name: "{{ __bootloader_packages }}"
    state: present

- name: Ensure required services are enabled and started
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ __bootloader_services }}"

- name: Generate /etc/{{ __bootloader_foo_config }}
  template:
    src: "{{ __bootloader_foo_config }}.j2"
    dest: /etc/{{ __bootloader_foo_config }}
    backup: yes
    mode: 0400
  notify: bootloader handler to restart services
