# SPDX-License-Identifier: MIT
---
# Put handlers for tasks here.

# Example:
- name: bootloader handler to restart services
  service:
    name: "{{ item }}"
    state: restarted
  loop: "{{ __bootloader_services }}"
